### ISSUE TITLE
Handle missing test.json gracefully

### ISSUE THREAD

**Issue by sagikazarmark** [guyarb/golang-test-annoations#14]
Jobs can fail for a thousand reasons and not all of them are related to tests.

In those cases a test.json is never created and this action fails trying to read that file. If no test.json exists, the action should just move on.

**Comment by guyarb** [comment]
Hey, i think i'll just add `if-no-files-found` option just like https://github.com/actions/upload-artifact has
thx!

**Comment by sagikazarmark** [comment]
In case of the upload action it probably makes sense to control this behavior, but for this action, I don't see why failing the build would ever make sense, so I'd argue it should be the default behavior.

**Comment by guyarb** [comment]
I fixed it and pushed it to the master branch
I'm no longer failing the job, instead i'm writing a warning

**Comment by sagikazarmark** [comment]
Awesome, thanks!
