### ISSUE TITLE
can you add a link to showing this

### ISSUE THREAD

**Issue by alexec** [guyarb/golang-test-annoations#4]

**Comment by guyarb** [comment]
hey @alexec!
Can you elaborate on your request? I didn't understand which link you are talking about, or where to add it

**Comment by alexec** [comment]
I'd like to see a build that is using this feature

**Comment by guyarb** [comment]
Updated the readme, now it contains a link to an example repo.

**Comment by alexec** [comment]
I get a 404 error:

https://github.com/guyarb/golang-test-annotations-example/actions/runs/505258482

**Comment by alexec** [comment]
Any chance you could take a look at my set-up:

https://github.com/argoproj/argo/pull/4925

I didn't seem to get errors reported.

**Comment by guyarb** [comment]
@alexec , i opened the example repo to be public :)

and it looks like the output of your UI tests are not in the format that `go test -json ./... > test.json`

can you post the `test.json` file from your CI?

**Comment by alexec** [comment]
maybe it is `gotestsum --jsonfile=test.json --` not working - I will investigate

**Comment by guyarb** [comment]
@alexec do you have any conclusions?

**Comment by alexec** [comment]
sorry - I gave up :(

**Comment by guyarb** [comment]
can you switch the test command line to `go test -json ./... > test.json`?

**Comment by displague** [comment]
@guyarb similar experience with https://github.com/equinix/terraform-provider-metal/pull/173/checks?check_run_id=3246845567

![image](https://user-images.githubusercontent.com/317653/129124750-7c755d07-86aa-4da2-bb5b-daf09a05ebe9.png)

The errors were not annotated to the PR view. I'm not sure if this would have to be merged first or if the PR introducing golang-test-annotations should have been annotated.

https://github.com/equinix/terraform-provider-metal/pull/173/files

**Comment by guyarb** [comment]
@displague , I do see the errors were annotated https://github.com/equinix/terraform-provider-metal/actions/runs/1099517484
![image](https://user-images.githubusercontent.com/17148247/129434584-86623ab5-c0c5-4ee4-b15c-d0423fcac218.png)
![image](https://user-images.githubusercontent.com/17148247/129434592-91f7a356-f291-422f-a864-8aaed55fb5a3.png)

did i misunderstand you?

**Comment by displague** [comment]
@guyarb I see what you mean.  I was expecting inline PR comments on failed tests, like https://github.com/reviewdog/reviewdog.

![image](https://user-images.githubusercontent.com/317653/129570436-7cc09124-06e0-4e8d-bf69-28b550ef5287.png)


Is the problem that the test file/function/lines were not modified in the PR? If they were, perhaps the annotation would appear on that function?

**Comment by displague** [comment]
Here's a better example of what I was expecting:

https://github.com/WillAbides/go-test2action/pull/1/files

https://github.com/WillAbides/go-test2action/blob/main/internal/internal.go
https://github.com/WillAbides/ezactions/blob/master/commander.go#L106 (looks like you can specify col= too)

**Comment by displague** [comment]
Perhaps https://github.com/isaacs/github/issues/284#issuecomment-860297388 is related and actions have no way to comment on lines (tests) that are not included in the PR.

**Comment by guyarb** [comment]
@displague, indeed when the PR added a failed test it adds preview on the diff (for [https://github.com/guyarb/golang-test-annotations-example/pull/1/files](https://github.com/guyarb/golang-test-annotations-example/pull/1/files))
