### ISSUE TITLE
Latest release missing from marketplace?

### ISSUE THREAD

**Issue by hairyhenderson** [guyarb/golang-test-annoations#6]
In the releases, `v0.4.0` is marked as latest: https://github.com/guyarb/golang-test-annotations/releases/tag/v0.4.0

But `v0.3.0` is the latest version that shows up in the marketplace: https://github.com/marketplace/actions/golang-test-annotations.

**Comment by guyarb** [comment]
@hairyhenderson, I forgot to mark the checkbox
It is available now
thanks!
