### ISSUE TITLE
Can't use 'package-name' parameter

### ISSUE THREAD

**Issue by mralves** [guyarb/golang-test-annoations#8]
I am using the version v0.4.0, when trying to specify the 'package-name' I see the warning:
```
Warning: Unexpected input(s) 'package-name', valid inputs are ['test-results']
```
It seems that 'package-name' is not defined in the [action.yaml](https://github.com/guyarb/golang-test-annotations/blob/master/action.yml)

**Comment by guyarb** [comment]
@mralves hey, ill take a look at it
Thanks
